site_name: Método RK4
nav:
  - Home: index.md
  - Explicación: explanation.md
  - Tutorial: tutorials.md
  - Referencia: reference.md
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

